#!/usr/bin/env bash
cd `dirname $0`
jar=`ls -t build/libs/*.jar | head -n 1`
echo $jar
mode="$1"
profile="$1"
if [ -z $profile ]; then
 profile=mongo-local
fi
export API_REST_HOST=localhost
export API_REST_PORT=8080
#export API_REST_HOST=dev-api-anomaly.ap-southeast-2.elasticbeanstalk.com
#export API_REST_PORT=80
echo running with profile  $profile
echo java -Dspring.profiles.active=$profile -jar $jar
java -Dspring.profiles.active=$profile -jar $jar
