#
# application-mongo.yml
#
spring:
  output:
    ansi:
      enabled: DETECT
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    jpa:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb+srv://nick:XMyTjyPqjJZFMBCN@rocket-pc4vk.mongodb.net/rocket