version: '3'

services:
 anomaly:
  image: dockerpathos/anomaly:1.1.6
  environment:
   - "SPRING_PROFILES_ACTIVE=mongo-docker"
   - "API_REST_HOST=localhost"
   - "API_REST_PORT=8080"
  ports: 
   - '8080:8080'
  links:
   - mongodb
  depends_on:
   - mongodb
 mongodb:
  image: mongo:3.4
  container_name: "mongodb"
  environment:
   - MONGO_INITDB_ROOT_USERNAME=mongoadmin
   - MONGO_INITDB_ROOT_PASSWORD=mongopass567
   - MONGO_INITDB_DATABASE=admin
  volumes:
   - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
   - ./mongo-volume:/data/db
  ports:
   - '27017:27017'
